In [12]:
from ProcessOptimizer import space
from ProcessOptimizer.learning import GaussianProcessRegressor
from ProcessOptimizer import Optimizer
from ProcessOptimizer.space import constraints
from ProcessOptimizer.space.constraints import Single, Inclusive, Exclusive, Constraints

In [13]:
from ProcessOptimizer.space import Integer, Categorical, Real
import numpy as np
np.random.seed(1234)

%matplotlib inline
import matplotlib.pyplot as plt
plt.set_cmap("viridis")

<Figure size 432x288 with 0 Axes>

In [14]:
def funny_func(x_list):
    s = 0
    for x in x_list:
        if type(x) == str:
            string_sum = 0
            for x_i in x:
                string_sum += ord(x_i)/100-0.7
            string_sum/= len(x)
            s+= string_sum
        else:
            s += x**2
    return s

In [15]:
SPACE = [
    Real(1, 10, name='max_depth',transform='normalize', prior = 'uniform'),
    Integer(0, 10, name='max_features'),
    Categorical(list('abcdefg'), name='dummy',transform='onehot'),
    Categorical(['gini', 1,'cool'], name='criterion'),
]


In [16]:
SPACE = [

    Categorical(('a','b','c'), name='dummy',transform='onehot'),
]

In [31]:
a=space.Space([(0.0,5.0),(0,5),['a','b','c']])

In [37]:
a.dimensions[1].rvs()

array([0])

In [39]:
cons_list = [Inclusive(0,(1.0,2.0),'real'),Inclusive(0,(3.0,4.0),'real'),Inclusive(0,(5.0,6.0),'real')]

In [41]:
hej = space.Space([
        Real(1, 10),
        Real(1, 10),
        Real(1, 10),
        Integer(0, 10),
        Integer(0, 10),
        Integer(0, 10),
        Categorical(list('abcdefg')),
        Categorical(list('abcdefg')),
        Categorical(list('abcdefg'))
    ])

In [42]:
cons = Constraints(cons_list,hej)

In [44]:
sample = [0]*hej.n_dims

In [46]:
cons.validate_sample(sample)

False

In [27]:
for i in a:
    print(i)

a


In [23]:
a.dimensions[2]

Categorical(categories=('a', 'b', 'c'), prior=None)

In [34]:
space.Space([[1,2],[1,2]])

Space([Integer(low=1, high=2),
       Integer(low=1, high=2)])

In [9]:
a = tuple(0)

TypeError: 'int' object is not iterable

In [10]:
Inclusive(-1,(1,2.0),'real')

Inclusive(dimension=-1, bounds=(1, 2.0), space_Type=real)

In [8]:
type(a)

int

In [5]:
cons = [constraints.Single(0,5.0,'real'),
    constraints.Inclusive(1,[1,3],'integer'),
    constraints.Exclusive(2,['a','b'],'categorical')]

In [6]:
opt = Optimizer(SPACE, "ET", acq_optimizer="sampling")

In [7]:
opt.constraints

In [8]:
next_x= opt.ask()
next_x

[5.478972998253845, 5, 'd', 'cool']

In [9]:
f_val = funny_func(next_x)
f_val

55.691645115594724

In [10]:
opt.tell(next_x, f_val)

          fun: 55.691645115594724
    func_vals: array([55.69164512])
       models: []
 random_state: <mtrand.RandomState object at 0x7fc25d39a3f0>
        space: Space([Real(low=1, high=10, prior='uniform', transform='normalize'),
       Integer(low=0, high=10),
       Categorical(categories=('a', 'b', 'c', 'd', 'e', 'f', 'g'), prior=None),
       Categorical(categories=('gini', 1, 'cool'), prior=None)])
        specs: None
            x: [5.478972998253845, 5, 'd', 'cool']
      x_iters: [[5.478972998253845, 5, 'd', 'cool']]

In [11]:
opt.add_constraints(cons)

In [38]:
opt.n_initial_points_

10

In [37]:
opt.next_xs_

[array([0.44444444, 5.        , 0.        , 0.        , 1.        ,
        0.        ]),
 array([0.44444444, 5.        , 0.        , 0.        , 1.        ,
        0.        ]),
 array([0.44444444, 5.        , 0.        , 0.        , 1.        ,
        0.        ])]

In [13]:
opt.remove_constraints()

In [16]:
cons = [constraints.Exclusive(0,[1,9]),
       constraints.Inclusive(1,[4,5])]
opt.add_constraints(cons)

In [18]:
cons = [constraints.Hard(0,2),
       constraints.Inclusive(1,[4,5]),
       constraints.Inclusive(2,['b'])]
opt.add_constraints(cons)

In [69]:
opt.ask()

constraints are not the same


[2.3595361718641708, 3, 'a', 'gini']

In [38]:
next_x= opt.ask(n_points = 3)

constraints are not the same


In [23]:
opt.constraints

[Hard(dimension=0, value=2),
 Inclusive(dimension=1, bounds=[4, 5]),
 Inclusive(dimension=2, bounds=['b'])]

In [24]:
hej.constraints

[Hard(dimension=0, value=2),
 Inclusive(dimension=1, bounds=[4, 5]),
 Inclusive(dimension=2, bounds=['b'])]

In [29]:
hej.ask()

[2.0, 4, 'b', 'entropy']

In [22]:
hej = opt.copy()

In [73]:
opt.constraints

[Hard(dimension=0, value=2),
 Inclusive(dimension=1, bounds=[4, 5]),
 Inclusive(dimension=2, bounds=['b'])]

In [18]:
c = opt.list_of_constraints[0]

In [19]:
d  =opt.constraints

In [12]:
type(opt.constraints)

NoneType

In [16]:
c == d

True

In [18]:
[0,1,2] == [[1,2],[3,2,1,'a']]

False

In [15]:
all([a == b for a, b in zip(c, d)])

TypeError: zip argument #1 must support iteration

In [23]:
next_x= opt.ask()
next_x

[1.6965080895465003, 3, 'a', 'gini']

In [26]:
opt.yi.pop()

12.483733800454678

In [27]:
opt.yi

[55.7205736870233,
 113.94440770743553,
 170.12417214601976,
 29.60805290886856,
 37.24926524880415,
 22.78091295592957,
 12.44463120849616,
 126.39874326258791,
 25.87805690070754,
 28.349953647106272,
 11.822359568254495,
 29.676473345364013]

In [28]:
opt.Xi.pop()

[1.6900395854697243, 3, 'a', 'gini']

In [29]:
opt.Xi

[[5.478972998253845, 5, 'b', 'entropy'],
 [8.019782273069234, 7, 'a', 'gini'],
 [8.33646640645902, 10, 'a', 'gini'],
 [5.381500990324963, 0, 'c', 'gini'],
 [6.050765674590625, 0, 'b', 'gini'],
 [3.6165569792968832, 3, 'b', 'entropy'],
 [1.678431174786789, 3, 'a', 'gini'],
 [5.0745682833703105, 10, 'c', 'gini'],
 [4.917990273402233, 1, 'a', 'entropy'],
 [5.1631894286068665, 1, 'a', 'entropy'],
 [1.481505844826302, 3, 'a', 'gini'],
 [3.612336272464679, 4, 'a', 'gini']]

In [25]:
next_x= opt.ask()
next_x

[2.0, 4, 'a', 'gini']

In [19]:
len(opt.list_of_constraints)

7

In [26]:
len(opt.yi)

6

In [29]:
len(opt.Xi)

6

In [24]:
dir(opt)

['Xi',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ask',
 '_cat_inds',
 '_check_y_is_valid',
 '_n_initial_points',
 '_non_cat_inds',
 '_tell',
 'acq_func',
 'acq_func_kwargs',
 'acq_optimizer',
 'acq_optimizer_kwargs',
 'add_constraints',
 'ask',
 'base_estimator_',
 'cache_',
 'cand_acq_funcs_',
 'constraints',
 'copy',
 'eta',
 'gains_',
 'list_of_constraints',
 'models',
 'n_initial_points_',
 'n_jobs',
 'n_points',
 'n_restarts_optimizer',
 'remove_constraints',
 'rng',
 'run',
 'space',
 'tell',
 'yi']

In [23]:
len(opt.xi)

AttributeError: 'Optimizer' object has no attribute 'xi'

In [16]:
opt.list_of_constraints

[[Hard(dimension=0, value=2),
  Inclusive(dimension=1, bounds=[4, 5]),
  Inclusive(dimension=2, bounds=['b', 'a'])],
 [Hard(dimension=0, value=2),
  Inclusive(dimension=1, bounds=[4, 5]),
  Inclusive(dimension=2, bounds=['b', 'a'])],
 [Hard(dimension=0, value=2),
  Inclusive(dimension=1, bounds=[4, 5]),
  Inclusive(dimension=2, bounds=['b', 'a'])]]

In [34]:
f_val = funny_func(next_x)
f_val

60.25795161352544

In [36]:
res = opt.tell(next_x, f_val)

In [37]:
res

          fun: 60.25795161352544
    func_vals: array([60.25795161, 60.25795161])
       models: []
 random_state: <mtrand.RandomState object at 0x7f8fb2b75480>
        space: Space([Real(low=1, high=10, prior='uniform', transform='normalize'),
       Integer(low=0, high=10),
       Categorical(categories=('a', 'b', 'c'), prior=None),
       Categorical(categories=('gini', 'entropy'), prior=None)])
        specs: None
            x: [6.598978939358488, 4, 'c', 'entropy']
      x_iters: [[6.598978939358488, 4, 'c', 'entropy'], [6.598978939358488, 4, 'c', 'entropy']]

In [22]:
cons1 = [constraints.Exclusive(0,[1,9]),
       constraints.Inclusive(1,[4,5]),
        constraints.Hard(1,1)]
#cons = [2]

In [23]:
cons2 = [constraints.Exclusive(0,[1,9]),
       constraints.Inclusive(1,[4,5]),
        constraints.Hard(1,1)]
#cons = [2]

In [24]:
for i in range(3):
    for j in range(3):
        print(str(cons1[i]==cons2[j])+' i='+str(i)+' j='+str(j))

True i=0 j=0
False i=0 j=1
False i=0 j=2
False i=1 j=0
True i=1 j=1
False i=1 j=2
False i=2 j=0
False i=2 j=1
True i=2 j=2


In [25]:
all([a == b for a, b in zip(cons1, cons2)])

True

In [12]:
'bounds' in cons2[2]

TypeError: argument of type 'Hard' is not iterable

In [ ]:
hasattr

In [18]:
hasattr(cons2[2],'value')

True

In [45]:
[0,1] == [0,2]

False

In [31]:
dir(opt.constraints[0])


['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'dimension',
 'type',
 'value']

In [18]:
opt.space

Space([Real(low=1, high=10, prior='uniform', transform='normalize'),
       Integer(low=0, high=10),
       Categorical(categories=('a', 'b', 'c'), prior=None),
       Categorical(categories=('gini', 'entropy'), prior=None)])

In [73]:
opt.remove_constraints()

In [14]:
from ProcessOptimizer.space import constraints

In [15]:
a = constraints.Constraints(cons,opt.space)

In [16]:
a.hard

[Hard(dimension=0, value=1), None, None, None]